name: flutter_application_api
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Library umum Flutter
  cupertino_icons: ^1.0.8

  # Networking & caching
  dio: ^5.0.0
  cached_network_image: ^3.3.1
  http: ^1.1.0

  # Fonts & UI
  google_fonts: ^6.3.2
  sizer: ^3.1.3
  loading_animation_widget: ^1.2.0

  # State management & router
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^14.2.0

  # Storage & utilities
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  getwidget: ^7.0.0

  # WebView
  webview_flutter: ^4.8.0
  webview_flutter_web: ^0.2.3+4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash.png
